# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portals < Formula
  desc ""
  homepage "https://ionic.io/portals"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.3.1/portals_Darwin_x86_64.tar.gz"
      sha256 "7439621d0a83bfbdf48b4690be9b8bc11acae61be248a956f806717f21bd6f7a"

      def install
        bin.install "portals"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.3.1/portals_Darwin_arm64.tar.gz"
      sha256 "4c0a6ae87bf5c4455f95ffa7ae1bcaff860c01bb19c4dd27651133b7f5a6b671"

      def install
        bin.install "portals"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.3.1/portals_Linux_x86_64.tar.gz"
      sha256 "04e995dce2ec8ea8c1d4b70dfd820b5bc3091a56d062a7e558b1e4f5990bf7c9"

      def install
        bin.install "portals"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.3.1/portals_Linux_arm64.tar.gz"
      sha256 "6e9687479f35233fc49e55ffb37153b545ae255784784dc89a6e084f3220186f"

      def install
        bin.install "portals"
      end
    end
  end

  test do
    system "#{bin}/portals --version"
  end
end
