# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portals < Formula
  desc ""
  homepage "https://ionic.io/portals"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.2.2/portals_Darwin_x86_64.tar.gz"
      sha256 "d71052d3c2ca98837ae1c7a62701bde2dc1da3de9869ee8556de94817cdd88d2"

      def install
        bin.install "portals"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.2.2/portals_Darwin_arm64.tar.gz"
      sha256 "e7b729fa0650fe3bef23e72a198219ca865c4162bea05ad240d0a222d2fbbbd7"

      def install
        bin.install "portals"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.2.2/portals_Linux_arm64.tar.gz"
      sha256 "276cd8c90a385c53861db4262a314a8dadd989d093c8f86f519ac6962a0cb7a5"

      def install
        bin.install "portals"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ionic-team/portals-cli-releases/releases/download/0.2.2/portals_Linux_x86_64.tar.gz"
      sha256 "bffbf8beb2ca651794b7823d589d8cab8acb2a29fc08b81628a5758cee850a14"

      def install
        bin.install "portals"
      end
    end
  end

  test do
    system "#{bin}/portals --version"
  end
end
